version: '3'

services:
  app:
    build:
      context: ../.
      dockerfile: ./build/app/Dockerfile
    restart: on-failure
    environment:
      WAIT_HOSTS: db:5432, kafka:9092
      DSN: ${DSN}
    ports: 
      - ${APP_PORT}:${APP_PORT}
    depends_on: 
      - db 
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  migrate:
    build:
      context: ../.
      dockerfile: ./build/migrate/Dockerfile
    restart: on-failure
    environment:
      WAIT_HOSTS: db:5432
      DSN: ${DSN}
    volumes:
      - ../migrations:/migrations
    depends_on: 
      - db
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
