version: '3'

services:
  app:
    build:
      context: ../.
      dockerfile: ./build/app/Dockerfile
    restart: on-failure
    environment:
      WAIT_HOSTS: db:5432
      DSN: ${DSN}
    ports: 
      - ${APP_PORT}:8123
    depends_on: 
      - db 
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432
  migrate:
    build:
      context: ../.
      dockerfile: ./build/migrate/Dockerfile
    restart: on-failure
    environment:
      WAIT_HOSTS: db:5432
      DSN: ${DSN}
    volumes:
      - ../migrations:/migrations
    depends_on: 
      - db 
